### ISSUE TITLE
Never ending message "The server is processing the action..." 

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/snweb_ynh#13]
### Describe the bug

The message in the Yunohost web admin "The server is processing the action..." never disappears although the installation completed successfully. The last three messages in the webadmin are:

```
Configuring a systemd service...
Storing the config file checksum...
Securing files and directories...
```
The Standardnotes web app appeared in the application list, I started using it and everything is working well, including syncing to mobile and desktop apps. So maybe just a display issue bug?

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.4
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

1. Install Standard Notes Web via the webadmin
2. Wait until it completes

### Logs

https://paste.yunohost.org/okerirewax

**Comment by FabianWilkens** [comment]
Hey,
thanks for reporting.

I just tried it myself.
Work until the end:

...
...
Configuring a systemd service...
Storing the config file checksum...
Securing files and directories...
Configuring log rotation...
Integrating service in YunoHost...
Starting a systemd service...
Configuring SSOwat...
Reloading nginx web server...
Waiting for service...
Installation of snweb__2 completed


If your WebApp is working it should been installed completly.

You can check the install log here:
`https://yourdomain.tld/yunohost/admin/#/tools/logs/`
If it was logged to the end.



So I belief it could be a one time fault from the install window of the webadmin.

**Comment by FabianWilkens** [comment]
If you have anything else, please reopen this issue or create a new one.
