### ISSUE TITLE
How to install more extensions?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/snweb_ynh#14]
I am curious how the admin can install extensions for all users to use. Cheers!

I have read this:

> A dedicated domain is requierd if you want to use extensions. notes.your-domain.tld/ -> Extension Manager is working your-domain.tld/notes/ -> Extension Manager is not working

But I do not understand. Our instance is at notes.trom.tf - this means I cannot manage the extensions?

I found this https://standardnotes.com/help/48/can-i-use-extensions-with-a-self-hosted-server and this https://docs.standardnotes.org/extensions/intro/ - so we should be able to add more extensions, but how?

**Comment by TROMsite** [comment]
As a user I see that I can add something like ttps://standardnotes-extensions.netlify.app/index.json to the "activation code". But has an expiring date. I'd like, as and admin, to make all extensions available for all users without an expiration date.

**Comment by FabianWilkens** [comment]
Hi @TROMsite ,
thanks for asking.
Yes with your domain you can use extensions.
If you have also installed snserver, you can use the extensions which are installed with this package.

After registration on this server you get an email with install instructions for extensions.

Maybe I have to edit the Readme a little bit 

Hope I could help.

**Comment by TROMsite** [comment]
Ah yes I see that's great! The email went into the spam folder that's why I missed that. I have a few follow up questions:

1. Is it possible not to advertise the "extended" account in the email? It looks confusing since it links  to https://standardnotes.com/features
2. Is it possible for the admin to enable these as default somehow? So that users don't have to set the extensions up by themselves?

**Comment by FabianWilkens** [comment]
> Ah yes I see that's great! The email went into the spam folder that's why I missed that. I have a few follow up

Hmm. Never had that on my system before.

> 
> 1. Is it possible not to advertise the "extended" account in the email? It looks confusing since it links  to https://standardnotes.com/features

Yes this is possible. You have to edit the email template file. But you have to do this after each update.
I can send you the file location later.
The reason I did include this part is the there are all extensions in the extended version.
Now you get only the open source extensions.

>
> 2. Is it possible for the admin to enable these as default somehow? So that users don't have to set the extensions up by themselves?

That was also my idea, but I could figure out how to do it yet.

**Comment by TROMsite** [comment]
> Hmm. Never had that on my system before.

Maybe is the content of the email with many links that looks suspicious....idk.

> Yes this is possible. You have to edit the email template file. But you have to do this after each update.
File: \opt\yunohost\snserver\live\app\views\user_mailer\welcome.html.erb

Ok I did that. Is fine for me to always keep it updated. Thanks!

> That was also my idea, but I could figure out how to do it yet.

You meant you could not figure out? Probably. That'd be cool to have it as such.

**Comment by TROMsite** [comment]
After I upgraded the server as you suggested, I tried to create a new account via the web app and add the repository https://notesync.trom.tf//extensions/repo.json but nothing happens. Does not work. But it works via the desktop app. So probably the web app needs to also be upgraded.

**Comment by TROMsite** [comment]
> File: `\opt\yunohost\snserver\live\app\views\user_mailer\welcome.html.erb`

After the last update I cannot see this file anymore. Something changed.

**Comment by FabianWilkens** [comment]
> 
> 
> After I upgraded the server as you suggested, I tried to create a new account via the web app and add the repository https://notesync.trom.tf//extensions/repo.json but nothing happens. Does not work. But it works via the desktop app. So probably the web app needs to also be upgraded.

Yes correct, I have found the same problem. Couldn't figure out how to fix this yet.


> 
> 
> > File: `\opt\yunohost\snserver\live\app\views\user_mailer\welcome.html.erb`
> 
> After the last update I cannot see this file anymore. Something changed.

Yes that right. There is no welcome mail in the new version. But i create a new site with instractions which should be accessable from the Yunohost Portal.

**Comment by TROMsite** [comment]
> Yes correct, I have found the same problem. Couldn't figure out how to fix this yet.

Ah ok. Maybe you need the also update the web client?

> Yes that right. There is no welcome mail in the new version. But i create a new site with instractions which should be accessable from the Yunohost Portal.

Ok that's not a big deal but could have been useful for new users. We too made a page for our instance https://trom.tf/notes/ explaining all that.

**Comment by FabianWilkens** [comment]
Hi
it took some time before I merged the upgrade to the latest version of snweb #20 this week.

How the extensions are installed is unlikely to change in the future.

**Comment by tio-trom** [comment]
Thanks for looking into it. Is fine....not ideal but if it can't be improved then it is ok.
