### ISSUE TITLE
Cannot install: ERROR - Unable to install snweb: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by jcn50** [YunoHost-Apps/snweb_ynh#29]
### Describe the bug

Cannot install:
**ERROR - Unable to install snweb: An error occurred inside the app installation script**

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.5 (stable)
- I have access to my server:  through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Try to install snweb.

### Expected behavior

Installation goes through.

### Logs

https://paste.yunohost.org/raw/pegabuwiso

**Comment by FabianWilkens** [comment]
Hi.
I will take a look.

So you have a problem with your memory during installation.


Can you check how much ram your VPS has and how much ram you have free.

**Comment by jcn50** [comment]
There is this in the logs:
```
2022-01-04 05:28:24,935: DEBUG - FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
2022-01-04 05:28:24,936: DEBUG - FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
2022-01-04 05:28:24,936: DEBUG - FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

However the machine has 3GB of vSwap available. Node.js probably needs more allocated memory:
`export NODE_OPTIONS=--max-old-space-size=$(free -tm | awk 'END{print $2}')`

**Comment by jcn50** [comment]
> Can you check how much ram your VPS has and how much ram you have free.

```
root@yunohost:~# free -tm
              total        used        free      shared  buff/cache   available
Mem:            734         129         285           2         318         485
Swap:          2815         269        2546
Total:         3550         399        2832
```

2.8GB free memory including the vSwap~

**Comment by FabianWilkens** [comment]
Yes.
There was the same fault at snserver_ynh.

Solved it with the same solution

**Comment by jcn50** [comment]
> Solved it with the same solution

Where is the solution? And what do I have to do?

**Comment by FabianWilkens** [comment]
> > Solved it with the same solution
> 
> Where is the solution? And what do I have to do?

 Did it here at snserver_ynh.
https://github.com/YunoHost-Apps/snserver_ynh/blob/master/scripts/install#L201


Will do it later here as well.

**Comment by jcn50** [comment]
Excellent!! Shall I close the issue?

**Comment by FabianWilkens** [comment]
Let's see if it fix your issues first

**Comment by jcn50** [comment]
> Let's see if it fix your issues first

OK I have ran the code from the SSH/CLI, and now I am installing again~~please wait~

**Comment by jcn50** [comment]
It's a different kind of failure now, logs here:
https://paste.yunohost.org/raw/moruqowowa

**Comment by jcn50** [comment]
Do you want access to my server for testing?

**Comment by jcn50** [comment]
I have tried many things but it doesn't work. I guess I will have to wait for your patch.

**Comment by FabianWilkens** [comment]
You can try and install with this command:
`sudo yunohost app install https://github.com/YunoHost-Apps/snweb_ynh/tree/fix-install`

If you get still the "JavaScript heap out of memory"fault,
you can try and increase `node_max_old_space_size=2048` in the "scripts/_common.sh"  file.

**Comment by jcn50** [comment]
**Hurray it went through with the command! Thanks a lot Fabian//**
