### ISSUE TITLE
Upgrade the 'snweb' app failed - Standard Notes (snweb) from 3.39.1ynh1 to 3.66.0ynh1

### ISSUE THREAD

**Issue by aarontrom** [YunoHost-Apps/snweb_ynh#50]
### Describe the bug

Upgrade the 'snweb' app failed - An error occurred inside the app upgrade script

### Context

- Hardware: VPS bought online
- YunoHost version: 11.0.9.15 (stable)
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
- Using, or trying to install package version/branch: Standard Notes (snweb) from 3.39.1~ynh1 to 3.66.0~ynh1
- If upgrading, current package version: Standard Notes (snweb) from 3.39.1~ynh1 to 3.66.0~ynh1

### Steps to reproduce

- Try to upgrade snweb via webmin.

### Expected behavior

Upgrade should be successfully done.

### Logs

https://paste.yunohost.org/raw/abutegewek

**Comment by FabianWilkens** [comment]
Should be fixed now.
Please try again.

**Comment by FabianWilkens** [comment]
This issue is for an old version.

Should be fixed. If there are still problems, please reopen or create a new issue.
