### ISSUE TITLE
Error on updating Standard Notes (snweb) from 3.39.1~ynh1 to 3.66.0~ynh1

### ISSUE THREAD

**Issue by Veehem** [YunoHost-Apps/snweb_ynh#51]
Sorry I'm not use to code writing
It's 2 days that I've error message when I try to update snweb

`Upgrading dependencies...
dpkg: warning: version 'v8.0.1' has bad syntax: version number does not start with digit
Building... ( This may take a while... )
[Error] Upgrade failed.
sh: 0: getcwd() failed: No such file or directory

This action broke dpkg/APT (the system package managers)... You can try to solve this issue by connecting through SSH and running `sudo apt install --fix-broken` and/or `sudo dpkg --configure -a`.`

**Comment by FabianWilkens** [comment]
Same problem
        dpkg: warning: version 'v8.0.1' has bad syntax: version number does not start with digit
        [Error] Upgrade failed.
        sh: 0: getcwd() failed: No such file or directory

_Originally posted by @Veehem in https://github.com/YunoHost-Apps/snweb_ynh/issues/52#issuecomment-1269594824_

Could you provide some logs?

**Comment by Veehem** [comment]
Here are the (very long) log
[Stnadard_notes_error.txt](https://github.com/YunoHost-Apps/snweb_ynh/files/9738803/Stnadard_notes_error.txt)

**Comment by FabianWilkens** [comment]
Looks like you are trying to do the upgrade from the master branch.

Upgrade should be possible from the testing branch.

**Comment by Veehem** [comment]
The problem is that I only work with the Yunohost (update) interface. I don't know how to use the terminal

**Comment by FabianWilkens** [comment]
Ahh ok.
I will merge the fix soon into master.
Than it should work.
I will inform you here.

**Comment by Veehem** [comment]
Thanks

**Comment by FabianWilkens** [comment]
Should be fixed now.
Please try again.

**Comment by Veehem** [comment]
Yes, thank you, it's fixed
